#!/bin/sh

sxhkd &
ulauncher --hide-window --no-window-shadow &
nitrogen --restore &
[ -x ~/.config/polybar/launch.sh ] &&  ~/.config/polybar/launch.sh  &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           3
bspc config focused_border_color \#3c3836
bspc config normal_border_color  \#1d2021

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefoxdeveloperedition desktop='^1'
bspc rule -a jetbrains-studio center=false
bspc rule -a polybar border=off manage=off
bspc rule -a sxiv state=flaoting center=true
bspc rule -a ulauncher focus=on

wmname LG3D
