#!/bin/sh

sxhkd &
blueman-applet &
ulauncher --hide-window --no-window-shadow &
nitrogen --restore &
nmgui &
pactl load-module module-switch-on-connect &

[ -x ~/.config/polybar/launch.sh ] &&  ~/.config/polybar/launch.sh  &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           3
bspc config focused_border_color \#3c3836
bspc config normal_border_color  \#1d2021

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

bspc rule -a firefoxdeveloperedition desktop='^1'
bspc rule -a jetbrains-studio center=false
bspc rule -a polybar border=off manage=off
bspc rule -a sxiv state=floating center=true
bspc rule -a ulauncher focus=on
bspc rule -a Lutris desktop=^10
bspc rule -a Steam desktop=^10
bspc rule -a "ro.exe" desktop=^10

steam_path=$HOME/.steam/steam
# this sed command removes everything but the digits
game_id=$(ls $steam_path/steamapps/appmanifest_*.acf | sed 's/[^0-9]*//g')

for id in $game_id; do
    bspc rule -a steam_app_$id desktop=^10 state=fullscreen
done

wmname LG3D
